FROM fedora:@FEDORA_VERSION@

LABEL maintainer="The KubeVirt Project <kubevirt-dev@googlegroups.com>"

RUN dnf install -y dnf-plugins-core && \
    dnf copr enable -y @kubevirt/libvirt-@LIBVIRT_VERSION@ && \
    dnf copr enable -y @kubevirt/qemu-@QEMU_VERSION@ && \
    dnf install -y \
      libvirt-daemon-driver-qemu-@LIBVIRT_VERSION@.fc@FEDORA_VERSION@ \
      libvirt-client-@LIBVIRT_VERSION@.fc@FEDORA_VERSION@ \
      libvirt-daemon-driver-storage-core-@LIBVIRT_VERSION@.fc@FEDORA_VERSION@ \
      qemu-kvm-@QEMU_VERSION@.fc@FEDORA_VERSION@ \
      genisoimage \
      selinux-policy selinux-policy-targeted \
      nftables \
      iptables \
      augeas && \
    dnf update -y libgcrypt && \
    dnf clean all

COPY augconf /augconf
RUN augtool -f /augconf

COPY libvirtd.sh /libvirtd.sh
RUN chmod a+x /libvirtd.sh

RUN for qemu in /usr/bin/qemu-system-*; do setcap CAP_NET_BIND_SERVICE=+eip $qemu; done

CMD ["/libvirtd.sh"]
