FROM fedora:@FEDORA_VERSION@

LABEL maintainer="The KubeVirt Project <kubevirt-dev@googlegroups.com>"

RUN dnf install -y dnf-plugins-core && \
    dnf copr enable -y @kubevirt/libvirt-@LIBVIRT_SOURCE_VERSION@ && \
    dnf copr enable -y @kubevirt/qemu-@QEMU_SOURCE_VERSION@ && \
    dnf copr enable -y @kubevirt/seabios-@SEABIOS_SOURCE_VERSION@ && \
    dnf install -y \
        libvirt-daemon-driver-qemu-@LIBVIRT_BINARY_VERSION@ \
        libvirt-client-@LIBVIRT_BINARY_VERSION@ \
        libvirt-daemon-driver-storage-core-@LIBVIRT_BINARY_VERSION@ \
        qemu-kvm-@QEMU_BINARY_VERSION@ \
        seabios-bin-@SEABIOS_BINARY_VERSION@ \
        seavgabios-bin-@SEABIOS_BINARY_VERSION@ \
        genisoimage \
        selinux-policy selinux-policy-targeted \
        nftables \
        iptables \
        procps-ng \
        findutils \
        augeas && \
    dnf update -y libgcrypt && \
    dnf clean all && \
    for arch in aarch64 ppc64 s390x x86_64; do \
        qemu="/usr/bin/qemu-system-$arch"; \
        test -f "$qemu" || continue; \
        # Allow qemu to bind to privileged ports \
        # From: https://github.com/kubevirt/kubevirt/pull/1138 \
        setcap CAP_NET_BIND_SERVICE=+eip "$qemu" && \
        # Needed for migration from old KubeVirt versions \
        # https://github.com/kubevirt/kubevirt/issues/4629 \
        ln -s "$qemu" /usr/libexec/qemu-kvm && \
        break; \
    done

COPY augconf /augconf
RUN augtool -f /augconf
