source hack/config

# Apply overrides from the environment
IMAGE_NAME="${IMAGE_NAME:-$CONF_IMAGE_NAME}"
FEDORA_VERSION="${CONF_FEDORA_VERSION:-$CONF_FEDORA_VERSION}"
LIBVIRT_VERSION="${LIBVIRT_VERSION:-$CONF_LIBVIRT_VERSION}"
QEMU_VERSION="${QEMU_VERSION:-$CONF_QEMU_VERSION}"
TARGET_ARCHITECTURES="${TARGET_ARCHITECTURES:-$CONF_TARGET_ARCHITECTURES}"

GIT_UNIX_TIMESTAMP=$(git show --format='%ct' | head -1)
GIT_TIMESTAMP=$(date --date="@${GIT_UNIX_TIMESTAMP}" '+%Y%m%d')
GIT_COMMIT=$(git describe --always)
TAG="${GIT_TIMESTAMP}-${GIT_COMMIT}"
DOCKER_PLATFORM="linux/$(echo "${TARGET_ARCHITECTURES}" | sed "s: :,linux/:g")"
